### ISSUE TITLE
[Issue]: Conformance

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rocDecode#249]
### Problem Description

Conformance on CI fails for 2 streams (GFX942) -- http://math-ci.amd.com/blue/organizations/jenkins/gfx942%2Fprecheckin%2FrocDecode/detail/develop/17/pipeline/261/
```
Conformance test completed on the 135 streams:
     - The number of passing streams is 133
     - The number of failing streams is 2
     - The number of streams that did not finish decoding is 0
```

Need this to pass to throw hard failures on errors on CI

### Operating System

ALL

### CPU

ALL

### GPU

AMD Instinct MI300A

### ROCm Version

ROCm 6.1.0

**Comment by jeffqjiangNew** [comment]
On MI300/Navi31/VCN4, the VCN FW version with the fix is DEC 6 and up.  On Navi2x/VCN3, the VCN FW version with the fix is DEC 3 and up. MI2xx/VCN2.6 FW is still being worked on.

GPU driver version with the fix is 1709904.

**Comment by kiritigowda** [comment]
@eidenyoshida -- Due to base machine driver versions some of our tests are failing on the CI. Could we please upgrade to the above mentioned drivers to test on the CI? Thanks!

**Comment by kiritigowda** [comment]
latest on the CI
```
Conformance test completed on the 135 streams:
     - The number of passing streams is 134
     - The number of failing streams is 1
     - The number of streams that did not finish decoding is 0
```

**Comment by kiritigowda** [comment]
Current TOT test results - http://math-ci.amd.com/blue/organizations/jenkins/mainline%2Fprecheckin%2FrocDecode/detail/develop/97/pipeline/539

```
Conformance test completed on the 135 streams:
     - The number of passing streams is 133
     - The number of failing streams is 2
     - The number of streams that did not finish decoding is 0
```

**Comment by jeffqjiangNew** [comment]
HEVC conformance test on MI250 node x1000c4s5b1n0, with ROCm 6.3 2008307 passed: 

Conformance test completed on the 135 streams:
     - The number of passing streams is 135
     - The number of failing streams is 0
     - The number of streams that did not finish decoding is 0

**Comment by kiritigowda** [comment]
@jeffqjiangNew will close this issue once we confirm the passing with CI

**Comment by kiritigowda** [comment]
@jeffqjiangNew - all tests passing on the CI now. Will add hard failure for CI if tests fail in the future.

```
Conformance test completed on the 135 streams:
     - The number of passing streams is 135
     - The number of failing streams is 0
     - The number of streams that did not finish decoding is 0
```
