### ISSUE TITLE
[Feature]: rocencode?

### ISSUE THREAD

**Issue by johnnynunez** [ROCm/rocDecode#463]
### Suggestion Description

exists rocencode?
https://community.amd.com/t5/ai/unlocking-new-horizons-in-ai-and-hpc-with-the-release-of-amd/ba-p/726434

**Comment by timchenggu123** [comment]
Hi @johnnynunez, thanks for reaching out! rocEncode is still currently in development. Please stay tuned for news and updates through AMD's official channels. Thanks!

**Comment by tcgu-amd** [comment]
Hi @johnnynunez, thanks for reaching out! rocEncode is still currently in development. Please stay tuned for news and updates through AMD's official channels. Thanks!
