### ISSUE TITLE
[Issue]: libva not found on Fedora

### ISSUE THREAD

**Issue by trixirt** [ROCm/rocDecode#477]
### Problem Description

libva-devel is installed on Fedora, but the build throws this error

-- AMD ROCm rocDecode -- unmet dependencies
CMake Error at CMakeLists.txt:330 (message):
  -- ERROR!: libva Not Found - please install
  libva-amdgpu-dev/libva-amdgpu-devel!

The cause is this line
https://github.com/ROCm/rocDecode/blob/develop/cmake/FindLibva.cmake#L26

va.h is installed to /usr/include/va/va.h

### Operating System

Fedora Rawhide

### CPU

ALL

### GPU

ALL

### ROCm Version

ROCm 6.3.0

**Comment by AryanSalmanpour** [comment]
Hi, @trixirt Please install the `libva-amdgpu-devel` package to proceed. rocDecode requires `libva-amdgpu-devel` for building. To install all other dependencies needed for rocDecode, run `python3 rocDecode-setup.py` before building the rocDecode.

**Comment by trixirt** [comment]
This package is not available on Fedora. libva-devel is. 
This will be a problem for anyone not using the AMDGPU repo's.
